"""Add association table and relationships

Revision ID: a21bdec0bef3
Revises: 59ede1707661
Create Date: 2025-12-13 13:23:31.773811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a21bdec0bef3'
down_revision = '59ede1707661'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_genre_association',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], name=op.f('fk_movie_genre_association_genre_id_genres')),
    sa.ForeignKeyConstraint(['movie_id'], ['movies.id'], name=op.f('fk_movie_genre_association_movie_id_movies')),
    sa.PrimaryKeyConstraint('movie_id', 'genre_id')
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_movies_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_movies_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('movie_genre_association')
    # ### end Alembic commands ###
